export const UserFollowersList = {
  ALL: 'ALL_USERS',
  FOLLOWINGS: 'MY_FOLLOWINGS',
  FOLLOWERS: 'MY_FOLLOWERS',
  NOT_FOLLOWED: 'NOT_FOLLOWED',
};

export const SavedStatus = {
  SAVED: 'SAVE',
  OVERWRITE: 'OVERWRITE',
  UNSAVED_CHANGES: 'UNSAVED_CHANGES',
  DELETE: 'DELETE_CHANGES',
};
